[package]
name = "pico"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
async-trait = "0.1.91"
serde_json = "1.0.151"
serenity = { version = "0.12.5", default-features = false, features = ["client", "gateway", "model", "http", "rustls_backend"] }
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
